FROM node:22-slim

WORKDIR /app

# Copie uniquement les fichiers de dépendances pour le cache
COPY package*.json ./

# Installe TOUTES les dépendances (inclut devDependencies)
RUN npm install

# Copie le reste du code source
COPY . .

EXPOSE 3000

# Lancement en mode dev
CMD ["npm", "run", "dev"]