services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"

  backend:
    image: nampiasilala/outils-photovoltaiques-backend 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back-outils-photovoltaique:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}

  frontend:
    image: nampiasilala/outils-photovoltaiques-frontend
    volumes:
      - ./front-outils-photovoltaique:/app
      - /app/node_modules 
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
