version: "3.9"

services:
  backend:
    build: ./back-outils-photovoltaique
    image: nampiasilala/outils-photovoltaiques-backend
    command: >
      sh -lc "
        python manage.py migrate &&
        python manage.py collectstatic --noinput || true &&
        gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
      "
    # aucun volumes ici

  frontend:
    build:
      context: ./front-outils-photovoltaique
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    image: nampiasilala/outils-photovoltaiques-frontend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    # aucun volumes ici
