# Utilise tes images Docker Hub (nampiasilala/...) pour backend et frontend.

# Monte le code local (volumes) pour travailler dessus.

# Ouvre les ports : db sur 5433:5432, backend 8000, frontend 3000.



version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    image: nampiasilala/outils-photovoltaiques-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432

  frontend:
    image: nampiasilala/outils-photovoltaiques-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
