# Generated by Django 5.2.3 on 2025-08-13 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametres", "00xx_remove_user_relation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parametresysteme",
            options={
                "verbose_name": "Paramètres système",
                "verbose_name_plural": "Paramètres système",
            },
        ),
        migrations.RemoveIndex(
            model_name="parametresysteme",
            name="parametres__user_id_2c18fc_idx",
        ),
        migrations.RemoveField(
            model_name="parametresysteme",
            name="h_solaire",
        ),
        migrations.AddField(
            model_name="parametresysteme",
            name="i_sec",
            field=models.FloatField(
                default=1.25,
                help_text="Facteur de sécurité sur le courant régulateur (ex. 1.25).",
                validators=[django.core.validators.MinValueValidator(1.0)],
            ),
        ),
        migrations.AddField(
            model_name="parametresysteme",
            name="s_max",
            field=models.FloatField(
                default=0.25,
                help_text="Seuil de surdimensionnement autorisé pour modules PV/batteries (0–1).",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="parametresysteme",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="parametresysteme",
            name="dod",
            field=models.FloatField(
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="parametresysteme",
            name="k_dimensionnement",
            field=models.FloatField(
                default=1.25, validators=[django.core.validators.MinValueValidator(1.0)]
            ),
        ),
        migrations.AlterField(
            model_name="parametresysteme",
            name="k_securite",
            field=models.FloatField(
                default=1.3, validators=[django.core.validators.MinValueValidator(1.0)]
            ),
        ),
        migrations.AlterField(
            model_name="parametresysteme",
            name="n_global",
            field=models.FloatField(
                default=0.75,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
