# Generated by Django 5.2.3 on 2025-08-08 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donnees_entree", "0002_alter_donneesentree_localisation_and_more"),
        (
            "equipements",
            "0004_alter_equipement_capacite_alter_equipement_categorie_and_more",
        ),
        ("parametres", "0002_alter_parametresysteme_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dimensionnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_calcul", models.DateTimeField(auto_now_add=True)),
                ("puissance_totale", models.FloatField()),
                ("capacite_batterie", models.FloatField()),
                ("nombre_panneaux", models.IntegerField()),
                ("nombre_batteries", models.IntegerField(default=0)),
                ("bilan_energetique_annuel", models.FloatField()),
                ("cout_total", models.FloatField()),
                (
                    "batterie_recommandee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dimensionnements_batterie",
                        to="equipements.equipement",
                    ),
                ),
                (
                    "cable_recommande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dimensionnements_cable",
                        to="equipements.equipement",
                    ),
                ),
                (
                    "entree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donnees_entree.donneesentree",
                    ),
                ),
                (
                    "onduleur_recommande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dimensionnements_onduleur",
                        to="equipements.equipement",
                    ),
                ),
                (
                    "panneau_recommande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dimensionnements_panneau",
                        to="equipements.equipement",
                    ),
                ),
                (
                    "parametre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parametres.parametresysteme",
                    ),
                ),
                (
                    "regulateur_recommande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dimensionnements_regulateur",
                        to="equipements.equipement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date_calcul"], name="dimensionne_date_ca_f49182_idx"
                    ),
                    models.Index(
                        fields=["user"], name="dimensionne_user_id_759e3b_idx"
                    ),
                    models.Index(
                        fields=["entree"], name="dimensionne_entree__5da47e_idx"
                    ),
                ],
            },
        ),
    ]
