# Generated by Django 5.2.3 on 2025-07-05 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donnees_entree', '0001_initial'),
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calcul', models.DateField(auto_now_add=True)),
                ('puissance_totale', models.FloatField()),
                ('capacite_batterie', models.FloatField()),
                ('nombre_panneaux', models.IntegerField()),
                ('bilan_energetique_annuel', models.FloatField()),
                ('cout_total', models.FloatField()),
                ('entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donnees_entree.donneesentree')),
                ('parametre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.parametresysteme')),
            ],
        ),
    ]
