# Generated by Django 5.2.3 on 2025-07-22 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionnements', '0001_initial'),
        ('equipements', '0003_alter_equipement_options_equipement_modele_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensionnement',
            name='batterie_recommandee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimensionnements_batterie', to='equipements.equipement'),
        ),
        migrations.AddField(
            model_name='dimensionnement',
            name='nombre_batteries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dimensionnement',
            name='panneau_recommande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimensionnements_panneau', to='equipements.equipement'),
        ),
        migrations.AddField(
            model_name='dimensionnement',
            name='regulateur_recommande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimensionnements_regulateur', to='equipements.equipement'),
        ),
    ]
