# Generated by Django 5.2.3 on 2025-08-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dimensionnements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dimensionnement",
            name="dimensionne_user_id_759e3b_idx",
        ),
        migrations.RemoveField(
            model_name="dimensionnement",
            name="user",
        ),
    ]
