# Generated by Django 5.2.3 on 2025-08-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dimensionnements",
            "0002_remove_dimensionnement_dimensionne_user_id_759e3b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dimensionnement",
            options={"ordering": ["-date_calcul"]},
        ),
    ]
