# Generated by Django 5.2.3 on 2025-07-30 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionnements', '0002_dimensionnement_batterie_recommandee_and_more'),
        ('donnees_entree', '0001_initial'),
        ('parametres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensionnement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dimensionnements_utilisateur', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='bilan_energetique_annuel',
            field=models.DecimalField(decimal_places=2, help_text='Bilan énergétique annuel en Wh', max_digits=12),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='capacite_batterie',
            field=models.DecimalField(decimal_places=2, help_text='Capacité batterie requise en Ah', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='cout_total',
            field=models.DecimalField(decimal_places=2, help_text='Coût total estimé en €', max_digits=12),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='date_calcul',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='entree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensionnements_entree', to='donnees_entree.donneesentree'),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='nombre_batteries',
            field=models.IntegerField(default=0, help_text='Nombre de batteries'),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='nombre_panneaux',
            field=models.IntegerField(help_text='Nombre de panneaux solaires'),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='parametre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensionnements_parametre', to='parametres.parametresysteme'),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='puissance_totale',
            field=models.DecimalField(decimal_places=2, help_text='Puissance totale (Onduleur) en W', max_digits=10),
        ),
    ]
