# Generated by Django 5.2.3 on 2025-07-30 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionnements', '0003_dimensionnement_user_and_more'),
        ('donnees_entree', '0001_initial'),
        ('parametres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionnement',
            name='bilan_energetique_annuel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='capacite_batterie',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='cout_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='date_calcul',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='entree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donnees_entree.donneesentree'),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='nombre_batteries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='nombre_panneaux',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='parametre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.parametresysteme'),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='puissance_totale',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dimensionnement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
