# Generated by Django 5.2.3 on 2025-08-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dimensionnements", "0003_alter_dimensionnement_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensionnement",
            name="nb_batt_parallele",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimensionnement",
            name="nb_batt_serie",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimensionnement",
            name="nb_pv_parallele",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimensionnement",
            name="nb_pv_serie",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimensionnement",
            name="topologie_batterie",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="dimensionnement",
            name="topologie_pv",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
