# Generated by Django 5.2.3 on 2025-08-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dimensionnements", "0004_dimensionnement_nb_batt_parallele_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensionnement",
            name="longueur_cable_global_m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimensionnement",
            name="prix_cable_global",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
