# Generated by Django 5.2.3 on 2025-07-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionnements', '0004_alter_dimensionnement_bilan_energetique_annuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionnement',
            name='date_calcul',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
