# Generated by Django 5.2.3 on 2025-07-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Utilisateur', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Actif', max_length=20),
        ),
    ]
