# Generated by Django 5.2.3 on 2025-08-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_department_user_role_user_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(db_index=True, default="Utilisateur", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(db_index=True, default="Actif", max_length=20),
        ),
    ]
