# Generated by Django 5.2.3 on 2025-08-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
    ]
