# Generated by Django 5.2.3 on 2025-08-08 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donnees_entree", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="donneesentree",
            name="localisation",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="donneesentree",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donnees_entree",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="donneesentree",
            index=models.Index(
                fields=["user", "localisation"], name="donnees_ent_user_id_6787fe_idx"
            ),
        ),
    ]
