# Generated by Django 5.2.3 on 2025-08-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donnees_entree", "0002_alter_donneesentree_localisation_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="donneesentree",
            name="donnees_ent_user_id_6787fe_idx",
        ),
        migrations.RemoveField(
            model_name="donneesentree",
            name="user",
        ),
        migrations.AddIndex(
            model_name="donneesentree",
            index=models.Index(
                fields=["localisation"], name="donnees_ent_localis_ab3651_idx"
            ),
        ),
    ]
