# Generated by Django 5.2.3 on 2025-08-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "donnees_entree",
            "0003_remove_donneesentree_donnees_ent_user_id_6787fe_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="donneesentree",
            name="h_solaire",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
