# Generated by Django 5.2.3 on 2025-08-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donnees_entree", "0004_donneesentree_h_solaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="donneesentree",
            name="h_vers_toit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donneesentree",
            name="priorite_selection",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cout", "Prioriser le coût minimal"),
                    ("quantite", "Prioriser le nombre minimal"),
                ],
                default="cout",
                max_length=10,
                null=True,
            ),
        ),
    ]
