# Generated by Django 5.2.3 on 2025-08-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InputHelp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("daily_consumption", "Consommation journalière (Wh)"),
                            ("peak_power", "Puissance max (W)"),
                            ("autonomy_days", "Jours d'autonomie"),
                            ("battery_voltage", "Tension batterie"),
                            ("location", "Localisation"),
                            ("irradiance", "Irradiation (kWh/m²/j)"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("unit", models.CharField(blank=True, default="", max_length=32)),
                (
                    "placeholder",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("help_html", models.TextField(blank=True, default="")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
