# Generated by Django 5.2.3 on 2025-08-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenus", "0002_seed_inputhelp"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("body_html", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.DeleteModel(
            name="InputHelp",
        ),
    ]
