# Generated by Django 5.2.3 on 2025-08-12 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("panneau_solaire", "Panneau solaire"),
                            ("batterie", "Batterie"),
                            ("regulateur", "Régulateur"),
                            ("onduleur", "Onduleur"),
                            ("cable", "Câble"),
                            ("disjoncteur", "Disjoncteur"),
                            ("parafoudre", "Parafoudre"),
                            ("support", "Support"),
                            ("boitier_jonction", "Boîtier de jonction"),
                            ("connecteur", "Connecteur"),
                            ("monitoring", "Monitoring"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("marque", models.CharField(blank=True, default="", max_length=64)),
                ("modele", models.CharField(blank=True, default="", max_length=100)),
                (
                    "nom_commercial",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("devise", models.CharField(default="MGA", max_length=8)),
                (
                    "puissance_W",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "capacite_Ah",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tension_nominale_V",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "vmp_V",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "voc_V",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "type_regulateur",
                    models.CharField(
                        blank=True,
                        choices=[("MPPT", "MPPT"), ("PWM", "PWM")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "courant_A",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pv_voc_max_V",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "mppt_v_min_V",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "mppt_v_max_V",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "puissance_surgeb_W",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "entree_dc_V",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "sortie_ac_V",
                    models.CharField(blank=True, default="230", max_length=16),
                ),
                (
                    "frequence_Hz",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "section_mm2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "ampacite_A",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
                ("datasheet_url", models.URLField(blank=True, default="")),
                ("meta", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Équipement",
                "verbose_name_plural": "Équipements",
                "indexes": [
                    models.Index(
                        fields=["categorie", "prix_unitaire"],
                        name="equipements_categor_ee9da6_idx",
                    ),
                    models.Index(
                        fields=["categorie", "puissance_W"],
                        name="equipements_categor_f5a0e9_idx",
                    ),
                    models.Index(
                        fields=["categorie", "capacite_Ah"],
                        name="equipements_categor_dc4353_idx",
                    ),
                    models.Index(
                        fields=["categorie", "courant_A"],
                        name="equipements_categor_43723a_idx",
                    ),
                    models.Index(
                        fields=["categorie", "ampacite_A"],
                        name="equipements_categor_407d6f_idx",
                    ),
                ],
            },
        ),
    ]
