# Generated by Django 5.2.3 on 2025-07-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_equipement', models.CharField(max_length=255)),
                ('puissance', models.FloatField()),
                ('tension', models.FloatField()),
                ('capacite', models.FloatField()),
                ('prix_unitaire', models.FloatField()),
            ],
        ),
    ]
