# Generated by Django 5.2.3 on 2025-07-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='categorie',
            field=models.CharField(default='Non spécifié', max_length=255),
        ),
    ]
