# Generated by Django 5.2.3 on 2025-08-29 14:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Utilisateur qui a créé l'équipement (NULL = ancien catalogue admin).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipements_crees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="equipement",
            index=models.Index(
                fields=["categorie", "created_by"],
                name="equipements_categor_735e7b_idx",
            ),
        ),
    ]
