# Generated by Django 5.2.3 on 2025-08-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipements", "0002_equipement_created_at_equipement_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipement",
            name="approuve_dimensionnement",
            field=models.BooleanField(
                default=False,
                help_text="Équipement approuvé pour être utilisé dans les calculs de dimensionnement public.",
            ),
        ),
    ]
