# Generated by Django 5.2.3 on 2025-07-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0002_equipement_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipement',
            options={'verbose_name_plural': 'Equipements'},
        ),
        migrations.AddField(
            model_name='equipement',
            name='modele',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AddField(
            model_name='equipement',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='capacite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='categorie',
            field=models.CharField(default='Général', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='puissance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='tension',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='type_equipement',
            field=models.CharField(choices=[('Panneau solaire', 'Panneau solaire'), ('Batterie', 'Batterie'), ('Onduleur', 'Onduleur'), ('Régulateur', 'Régulateur')], max_length=50),
        ),
    ]
