# Generated by Django 5.2.3 on 2025-08-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipements", "0003_alter_equipement_options_equipement_modele_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipement",
            name="capacite",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("Général", "Général"),
                    ("Spécial", "Spécial"),
                    ("Autre", "Autre"),
                ],
                db_index=True,
                default="Général",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="modele",
            field=models.CharField(db_index=True, default="Standard", max_length=100),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="puissance",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="tension",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="type_equipement",
            field=models.CharField(
                choices=[
                    ("Panneau solaire", "Panneau solaire"),
                    ("Batterie", "Batterie"),
                    ("Onduleur", "Onduleur"),
                    ("Régulateur", "Régulateur"),
                    ("Câble", "Câble"),
                    ("Disjoncteur", "Disjoncteur"),
                    ("Parafoudre", "Parafoudre"),
                    ("Support", "Support"),
                    ("Boîtier de jonction", "Boîtier de jonction"),
                    ("Connecteur", "Connecteur"),
                    ("Monitoring", "Monitoring"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="equipement",
            index=models.Index(
                fields=["type_equipement", "modele"],
                name="equipements_type_eq_de9db9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="equipement",
            index=models.Index(
                fields=["categorie", "prix_unitaire"],
                name="equipements_categor_ee9da6_idx",
            ),
        ),
    ]
